signals:
  app:
    use: true
    NN: 8
    coreset: 1
    cleanse_scorename: "aerecon"
    percentile_cleanse: 75

  mot:
    use: true
    NN: 8
    coreset: 1
    cleanse_scorename: "gmm"
    percentile_cleanse: 75


postprocess:
  sigma: 5


xai:
  use: true
  method: tcav
